version: "3.8"
services:

  microgen-dockerapp:
    image: cchacin/microgen-dockerapp
    volumes:
      - dist_prometheus:/mp/prometheus
      - dist_grafana_provisioning:/mp/grafana/provisioning
      - dist_grafana_dashboards:/mp/grafana/dashboards
      - dist_postgres:/mp/postgres
      - dist_keycloack:/mp/keycloack

  portainer:
    image: portainer/portainer:1.24.1-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/portainer_password:/tmp/portainer_password
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock --no-auth

  jaeger:
    image: jaegertracing/all-in-one:1.21.0
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
    networks:
      - application-network

  prometheus:
    image: prom/prometheus:v2.24.1
    volumes:
      - dist_prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: always
    depends_on:
      - microgen-dockerapp
      - application
    links:
      - application
    networks:
      - application-network

  grafana:
    image: grafana/grafana:7.4.1
    user: "104"
    ports:
      - 3000:3000
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - dist_grafana_provisioning:/etc/grafana/provisioning/
      - dist_grafana_dashboards:/var/lib/grafana/dashboards/
    depends_on:
      - microgen-dockerapp
    links:
      - prometheus
    networks:
      - application-network

  postgres:
    image: library/postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - application-network

  pgadmin:
    image: dpage/pgadmin4:4.30
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /tmp/pgadmin4/servers.json
    volumes:
      - dist_postgres:/tmp/pgadmin4
    ports:
      - 5050:80
    restart: always
    depends_on:
      - microgen-dockerapp
    links:
      - postgres
    networks:
      - application-network

  application:
    image: ccchacin/myservice:1.0-SNAPSHOT
    depends_on:
      - postgres
    ports:
      - 9111:8080
    restart: always
    links:
      - jaeger
      - postgres
      - keycloak
    networks:
      - application-network

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    environment:
      DB_VENDOR: h2
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_IMPORT: /tmp/realms.json
    volumes:
      - dist_keycloack:/tmp
    depends_on:
      - microgen-dockerapp
    ports:
      - 8084:8080
    restart: always
    networks:
      - application-network

networks:
  application-network:
    name: application-network
volumes:
  dist_prometheus:
  dist_grafana_dashboards:
  dist_grafana_provisioning:
  dist_postgres:
  dist_keycloack:
