global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'application'
    scrape_interval: 15s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['application:8080']
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: '(application_)(.*)(_request_seconds)'
      replacement: '${2}'
      target_label: endpoint
    - source_labels: [__name__]
      regex: '(application_)(.*)(_request_seconds)'
      replacement: '${1}REST'
      target_label: __name__
