global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'traefik2'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['traefik:8080']
  - job_name: 'application'
    scrape_interval: 5s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['application:8080']
