{
 "title": "Java Quarkus Micrometer",
 "description": "Quarkus metrics exposed with Micrometer",
 "tags": [
  "java",
  "micrometer",
  "quarkus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Agroal Datasource Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "agroal_active_count", "legendFormat": "{{datasource}} Active" },
      { "expr": "agroal_available_count", "legendFormat": "{{datasource}} Available" },
      { "expr": "agroal_awaiting_count", "legendFormat": "{{datasource}} Awaiting" }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "agroal_max_used_count" }
     ]
    },
    {
     "title": "Acquire Time (Milliseconds)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(agroal_acquire_count_total[1m])",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Creation Time (Milliseconds)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "agroal_creation_time_average_milliseconds",
       "legendFormat": "AVG"
      },
      {
       "expr": "agroal_creation_time_max_milliseconds",
       "legendFormat": "MAX"
      },
      {
       "expr": "agroal_creation_time_total_milliseconds",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Blocking Time (Milliseconds)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "agroal_blocking_time_average_milliseconds",
       "legendFormat": "AVG"
      },
      {
       "expr": "agroal_blocking_time_max_milliseconds",
       "legendFormat": "MAX"
      },
      {
       "expr": "agroal_blocking_time_total_milliseconds",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Destroyed/Flushed/Invalid",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(agroal_destroy_count_total[1m])",
       "legendFormat": "DESTROY"
      },
      {
       "expr": "rate(agroal_flush_count_total[1m])",
       "legendFormat": "FLUSH"
      },
      {
       "expr": "rate(agroal_invalid_count_total[1m])",
       "legendFormat": "INVALID"
      }
     ]
    }
   ]
  },
  {
   "title": "Uptime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Uptime",
     "type": "stat",
     "description": "The uptime of the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "process_uptime_seconds" }
     ]
    },
    {
     "title": "Process Start Time",
     "type": "stat",
     "description": "The starttime of the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processor Count",
     "type": "stat",
     "description": "The number of processors available to the Java virtual machine",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "system_cpu_count" }
     ]
    },
    {
     "title": "Average CPU Load",
     "type": "graph",
     "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "system_cpu_usage" }
     ]
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Bytes READ vs WRITTEN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_bytes_read_count[1m])",
     "legendFormat": "Bytes Read"
    },
    {
     "expr": "rate(http_server_bytes_written_count[1m])",
     "legendFormat": "Bytes Written"
    }
   ]
  },
  {
   "title": "# HTTP Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_connections_seconds_active_count",
     "legendFormat": "Active Connections"
    },
    {}
   ]
  },
  {
   "title": "HTTP Request per Second (1m rate)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "reqps", "label": "Request / Second" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{outcome=\"SUCCESS\"}[1m])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{outcome=\"REDIRECTION\"}[1m])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{outcome=\"CLIENT_ERROR\"}[1m])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{outcome=\"SERVER_ERROR\"}[1m])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Request Processing Time",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{outcome=\"SUCCESS\"}",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{outcome=\"REDIRECTION\"}",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{outcome=\"CLIENT_ERROR\"}",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{outcome=\"SERVER_ERROR\"}",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "JVM Thread Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threads Peak",
     "type": "graph",
     "description": "The peak live thread count since the Java virtual machine started or peak was reset",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_peak_threads" }
     ]
    },
    {
     "title": "Live Daemon Threads",
     "type": "graph",
     "description": "The current number of live daemon threads",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_daemon_threads" }
     ]
    },
    {
     "title": "Live Total Threads",
     "type": "graph",
     "description": "The current number of live threads including both daemon and non-daemon threads",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_live_threads" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Count",
     "type": "graph",
     "description": "An estimate of the number of buffers in the pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_buffer_count_buffers", "legendFormat": "{{id}}" }
     ]
    },
    {
     "title": "Buffer Mem Used",
     "type": "graph",
     "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "{{id}}" }
     ]
    },
    {
     "title": "Buffer Capacity",
     "type": "graph",
     "description": "An estimate of the total capacity of the buffers in this pool",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_total_capacity_bytes",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Max Memory",
     "type": "graph",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "jvm_memory_max_bytes", "legendFormat": "{{id}} ({{area}})" }
     ]
    },
    {
     "title": "Used Memory",
     "type": "graph",
     "description": "The amount of used memory",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}} ({{area}})" }
     ]
    },
    {
     "title": "Committed Memory",
     "type": "graph",
     "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "jvm_memory_committed_bytes", "legendFormat": "{{id}} ({{area}})" }
     ]
    }
   ]
  },
  {
   "title": "JVM Garbage Collection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Data Size",
     "type": "graph",
     "description": "Max size of old generation memory pool",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "jvm_gc_max_data_size_bytes", "legendFormat": "{{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Live Data Size",
     "type": "graph",
     "description": "Size of old generation memory pool after a full GC",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "jvm_gc_live_data_size_bytes", "legendFormat": "{{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Promotion Rate",
     "type": "graph",
     "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Allocation Rate",
     "type": "graph",
     "description": "Incremented for an increase in the size of the young generation memory pool after one GC to before the next",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Pause Count",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "jvm_gc_pause_seconds_count", "legendFormat": "{{cause}} ({{action}})" }
     ]
    },
    {
     "title": "Pause Duration",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "jvm_gc_pause_seconds_sum", "legendFormat": "{{cause}} ({{action}})" }
     ]
    }
   ]
  },
  {
   "title": "Class Loader Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes Loaded",
     "type": "graph",
     "description": "The number of classes that are currently loaded in the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_classes_loaded_classes" }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "description": "The total number of classes unloaded since the Java virtual machine has started execution",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_classes_unloaded_classes_total[$__rate_interval])"
      }
     ]
    }
   ]
  }
 ]
}