{
 "title": "Microprofile Base Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "base_jvm_uptime_seconds" }
   ]
  },
  {
   "title": "Available Processors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "base_cpu_availableProcessors" }
   ]
  },
  {
   "title": "System Load Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "base_cpu_systemLoadAverage" }
   ]
  },
  {
   "title": "CPU Load Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "base_memory_maxHeap_bytes", "legendFormat": "Max" },
    { "expr": "base_memory_usedHeap_bytes", "legendFormat": "Used" }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_thread_count", "legendFormat": "Count" },
    { "expr": "base_thread_daemon_count", "legendFormat": "Daemon" },
    { "expr": "base_thread_max_count", "legendFormat": "Max" }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "base_gc_time_total_seconds{name=\"G1 Old Generation\"}",
     "legendFormat": "G1 Old Generation"
    },
    {
     "expr": "base_gc_time_total_seconds{name=\"G1 Young Generation\"}",
     "legendFormat": "G1 Young Generation"
    }
   ]
  },
  {
   "title": "GC Counts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(base_gc_total{name=\"G1 Old Generation\"}[5m])",
     "legendFormat": "G1 Old Generation"
    },
    {
     "expr": "rate(base_gc_total{name=\"G1 Young Generation\"}[5m])",
     "legendFormat": "G1 Young Generation"
    }
   ]
  }
 ]
}