{
 "title": "Microprofile Base Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "METHOD",
    "label": "METHOD",
    "query": {
     "query": "http_server_requests_seconds_count"
    }
   },
   {
    "name": "PATH",
    "label": "PATH",
    "query": {
     "query": "http_server_requests_seconds_count"
    }
   },
   {
    "name": "RESPONSE",
    "label": "RESPONSE",
    "query": {
     "query": "http_server_requests_seconds_count"
    }
   },
   {
    "name": "INTERVAL",
    "label": "INTERVAL",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "r",
    "query": {
     "query": "http_server_requests_seconds_count"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "r",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"$METHOD\", uri=\"$PATH\", outcome=\"$RESPONSE\"}[$INTERVAL])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "base_jvm_uptime_seconds" }
   ]
  },
  {
   "title": "Available Processors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "base_cpu_availableProcessors" }
   ]
  },
  {
   "title": "System Load Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "base_cpu_systemLoadAverage" }
   ]
  },
  {
   "title": "CPU Load Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "base_memory_maxHeap_bytes", "legendFormat": "Max" },
    { "expr": "base_memory_usedHeap_bytes", "legendFormat": "Used" }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_thread_count", "legendFormat": "Count" },
    { "expr": "base_thread_daemon_count", "legendFormat": "Daemon" },
    { "expr": "base_thread_max_count", "legendFormat": "Max" }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "base_gc_time_total_seconds{name=\"G1 Old Generation\"}",
     "legendFormat": "G1 Old Generation"
    },
    {
     "expr": "base_gc_time_total_seconds{name=\"G1 Young Generation\"}",
     "legendFormat": "G1 Young Generation"
    }
   ]
  },
  {
   "title": "GC Counts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(base_gc_total{name=\"G1 Old Generation\"}[5m])",
     "legendFormat": "G1 Old Generation"
    },
    {
     "expr": "rate(base_gc_total{name=\"G1 Young Generation\"}[5m])",
     "legendFormat": "G1 Young Generation"
    }
   ]
  }
 ]
}